### ISSUE TITLE
Exception on Huawei Device with Oreo

### ISSUE THREAD

**Issue by nerone-github** [nerone-github/LocalSpeedcam#1]
Probably a general issue, just creating a note for it:

```java

12-24 09:51:45.731 15775-15775/? E/AndroidRuntime: FATAL EXCEPTION: main
  Process: org.openauto.localspeedcam, PID: 15775
  java.lang.RuntimeException: Unable to create service org.openauto.localspeedcam.CarService: java.lang.RuntimeException: com.google.android.gms.car.b: java.lang.reflect.InvocationTargetException
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3855)
      at android.app.ActivityThread.-wrap5(Unknown Source:0)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979)
      at android.os.Handler.dispatchMessage(Handler.java:108)
      at android.os.Looper.loop(Looper.java:166)
      at android.app.ActivityThread.main(ActivityThread.java:7393)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
   Caused by: java.lang.RuntimeException: com.google.android.gms.car.b: java.lang.reflect.InvocationTargetException
      at com.google.android.gms.car.d.onCreate(Unknown Source:36)
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3835)
      at android.app.ActivityThread.-wrap5(Unknown Source:0) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979) 
      at android.os.Handler.dispatchMessage(Handler.java:108) 
      at android.os.Looper.loop(Looper.java:166) 
      at android.app.ActivityThread.main(ActivityThread.java:7393) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
   Caused by: com.google.android.gms.car.b: java.lang.reflect.InvocationTargetException
      at com.google.android.gms.car.a.a(Unknown Source:36)
      at com.google.android.gms.car.d.onCreate(Unknown Source:12)
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3835) 
      at android.app.ActivityThread.-wrap5(Unknown Source:0) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979) 
      at android.os.Handler.dispatchMessage(Handler.java:108) 
      at android.os.Looper.loop(Looper.java:166) 
      at android.app.ActivityThread.main(ActivityThread.java:7393) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
   Caused by: java.lang.reflect.InvocationTargetException
      at java.lang.reflect.Method.invoke(Native Method)
      at com.google.android.gms.car.a.a(Unknown Source:26)
      at com.google.android.gms.car.d.onCreate(Unknown Source:12) 
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3835) 
      at android.app.ActivityThread.-wrap5(Unknown Source:0) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979) 
      at android.os.Handler.dispatchMessage(Handler.java:108) 
      at android.os.Looper.loop(Looper.java:166) 
      at android.app.ActivityThread.main(ActivityThread.java:7393) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
   Caused by: java.lang.RuntimeException: Failed to find impl
      at com.google.android.gms.car.ImplStager.a(SourceFile:20)
      at com.google.android.gms.car.DynamicApiFac
```

**Comment by nerone-github** [comment]
Bug in ROM
